#!/bin/sh
echo "Instalando osrmint en $(pg_config --version)"
SHARE_DIR=$(pg_config --sharedir)
PKGLIB_DIR=$(pg_config --pkglibdir)
sudo cp build/osrmint-0.1.so $PKGLIB_DIR/
sudo cp sql/osrmint.sql $SHARE_DIR/extension/osrmint--0.1.sql
sudo cp control/osrmint.control $SHARE_DIR/extension/
