#!/bin/bash
DBUSER=postgres
DBHOST=localhost
DBPORT=5432
DBNAME=osrminttest

psql -h $DBHOST -U $DBUSER -p $DBPORT -d template1 -c "DROP DATABASE $DBNAME;"
psql -h $DBHOST -U $DBUSER -p $DBPORT -d template1 -c "CREATE DATABASE $DBNAME;"
psql -h $DBHOST -U $DBUSER -p $DBPORT -d $DBNAME < osrminttest.sql
